# favicon.ico is converted by using GIMP from https://github.com/xterm-x11/xterm-snapshots/blob/master/icons/xterm-color.png (the .svg file is a bit corrupted)
site_name: XTerm
site_url: https://xterm.org
nav:
  - 'Home': index.md
  - 'Story': story.md
  - 'Install':
       - 'Package': package.md
       - 'xterm.tar.gz': xterm.tar.gz.md
  - 'Configure': configure.md
  - 'Get started':
       # Select content from
       # https://invisible-island.net/xterm/xterm.faq.html
       # and
       # https://invisible-island.net/xterm/#related-discussion
       # Figure out a way to reference the manpage from each separate procedure page under Use,
       # where applicable.
       - 'Copy-paste': copy-paste.md
       - 'Tabs': tabs.md
       - 'Full-screen': full-screen.md
       - 'Scrolling': scrolling.md
       - 'Prompt': prompt.md
       - 'Dynamic window title': dynamic-window-title.md
  - 'Customize':
       - 'Sample': sample.md
       - 'Themes': themes.md
       - 'Template': template.md
       - 'Icon': icon.md
       - 'Static window title': static-window-title.md
       - 'Scrollbar': scrollbar.md
       - 'Internal border': internal-border.md
       - 'Window border': window-border.md
  - 'Control sequences':
       - 'Getting started with control sequences': getting-started-with-ctlseqs.md
       - 'Guide': ctlseqs-guide.md
       - 'List': ctlseqs-list.md
  - 'Manpage':
       - 'xterm': manpage-xterm.md
       - 'uxterm': manpage-uxterm.md
       - 'koi8rxterm': manpage-koi8rxterm.md
       - 'resize': manpage-resize.md
  - 'Release notes': release-notes.md
  - 'Libraries':
       - 'Xcursor': xcursor.md
       - 'Xft': xft.md
  - 'Utilities':
       - 'Vttest':
           - 'About Vttest': vttest_about.md
           - 'Vttest changes': vttest-changes.md
           - 'Xtoolkit': xtoolkit.md # check if this should instead be under Libraries
       - 'Luit': 'luit.md'

theme:
  name: material
  favicon: favicon.png
  logo: logo-favicon.png # https://github.com/xterm-x11/xterm-snapshots/blob/master/icons/xterm-color.png (the .svg file is a bit corrupted)
repo_url: https://github.com/xterm-x11/docs
plugins:
  - search
